services:
  - type: web
    name: atelier-gestion-projets-py
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    disk:
      name: atelier-projets-py-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
